### PR TITLE
Install PSP/PSX games on ux0, uma0, or ur0

### PR DESCRIPTION
**Pull request by jonofarc**
This is a branch I worked on its my first time doing work for the psp vita any feed back its appreciated,

I added the ability to chose where you want your psp or psx games to be installed by pressing select button to changed the directory, if the user is already on the psp or psx game list, the list will autorefresh to properly display wich games are currently installed and will display free space of that storage, if the user is not on psp or psx games the free space will continue displaying ux0: changing storage while a game is downloading is disabled to avoid conflicts during game installation, games will donwload on the proper storage device while downloading (ux0:pkgi, uma0:pkgi, or ur0:pkgi) psx and psp games can be installed to ux0, uma0 or ur0.

uma0
ux0
ur0

### CODE REVIEW

**Comment by jonofarc** [comment]
Thanks for the feedback I will see if I can address the issues soon as the ability to chose where the psp and psx games get downloaded for adrenaline was something I really wanted

**Comment by blastrock** [comment]
I may have some free time in the coming days, do you want me to take this over and finish the feature?

**Comment by jonofarc** [comment]
I dont have time this weekend but I would like to flesh this out myself, if by Friday 12 I haven't finished it I would of course accept you finish it but I would appreciate a chance to finish it.

**Comment by blastrock** [comment]
Alright, no problem :)

**Comment by blastrock** [comment]
superseded by #72

**Pull request closed without merging**
