### PR TITLE
try loading tsv from local first

### PR DESCRIPTION
**Pull request by soarqin**

### CODE REVIEW

**Comment by andoryuu3** [comment]
You mean load the locally cached tsv before the one on the web? I suppose there might be a benefit if a certain website that hosts the popular tsv files ever goes down, but other than that... I don't see the point because you've got to be connected to the internet to download anything.

**Comment by soarqin** [comment]
tsv's loaded from url set in config.txt are not cached locally, so that this commit won't affect normal users.
The change is only used with poor connections to certain tsv providers' websites(PSN do have CDN globally so that download official pkg would not be too slow) so that people could load tsv from local ux0:/pkgi/

**Comment by blastrock** [comment]
Wow, this is an old PR from the time github didn't send me mails >< Sorry I'm seeing it only now.

I will be removing the `content` part of this function, it makes no sense to have an http function load a file from disk. It will make the code more modular, reusable and testable, but it will break your patch.

I still have in mind to avoid redownloading the TSV file every time, but I was planning on doing it more transparently, along the lines of #15; the database would be redownloaded only when asked by the user, and loaded from memory the rest of the time. I may be using a sqlite database for that as it will help with filtering, I'm not decided yet though.

I will leave this PR open in the meantime for people who might want to cherry-pick your commit.

**Comment by soarqin** [comment]
@blastrock okay, I will close this first. waiting for your changes

**Pull request closed without merging**
