### PR TITLE
Add PSM Support

### PR DESCRIPTION
**Pull request by baregl**
Adds support for psm. Mostly just doing what pkg2zip does.

### CODE REVIEW

**Comment by baregl** [comment]
Thanks for the review.
Sorry for the big commit, this grew somewhat organically and there wasn't a good point to commit in between.
AFAIK the rebuild option in the recovery menu also resets the layout. The "Easy Power Refresh" app also needs a restart, but the livearea layout is kept. They call "os.updatedb()", but their lua interpreter is closed source and I can't find something similar in the vitasdk.
It seems kind of hacky and I would just defer the issue, maybe a pointer in the readme.

**Comment by baregl** [comment]
I've found SwitchSD2Vita and [they](https://github.com/Applelo/SwitchSD2Vita/blob/bc531f7cf037d7647b308352cd4c32a139704416/src/Engine.cpp#L268) trigger the database update by removing the id.dat file from the root of the storage card. Maybe just do that and add a message asking the user to reboot to see the game?

**Comment by blastrock** [comment]
That last option seems way too risky to me, I'm sure people will lose data.

I guess people will be ok with losing their layout if they can install psm games... Here's a suggestion: you write a section in the readme explaining how to do that stuff, and you add a config option that must go like `psm_disclaimer_i_hereby_confirm_that_i_have_read https://github.com/blastrock/pkgj#setup-instructions-for-psm-games`. I fear that a lot of people will open issues saying that psm games do not work, so it may help with that.

**Comment by baregl** [comment]
Something I just noticed: When having all urls enabled, the menu is too large for the vita screen. I only see two obvious solutions: Removing the padding at the top (or reducing it) or coalescing the refresh & refresh comp pack options into one (I see little reason to have them as separate menu items)

**Comment by baregl** [comment]
I wouldn't put a link to the readme in the config option, since:
1. It should be pretty obvious what should be read
2. Putting the url there wouldn't help (much), since i imagine some (most) people edit the file on the vita
3. I think it's kind of "dirty" to secretly depend on the repo url

Maybe just add an obvious "and_i_know_i_have_to_refresh_livearea_for_psm_games_to_appear"?

**Comment by blastrock** [comment]
> Something I just noticed: When having all urls enabled, the menu is too large for the vita screen. I only see two obvious solutions: Removing the padding at the top (or reducing it) or coalescing the refresh & refresh comp pack options into one (I see little reason to have them as separate menu items)

I will need to improve the whole gui anyway, that's on my todo list, so I would suggest just doing the easiest thing: reduce the padding between the items, or at the top of the menu, as you prefer.
Merging the refresh options isn't the point of this PR, so let's leave it for later.

> I wouldn't put a link to the readme in the config option

All right, it makes sense. I guess what you just pushed is ok, we can leave that.

I will try to test your PR this weekend, fix the CI (the bzip.org domain has expired, so conan can't download the sources anymore) and merge this if everything is ok. Thank you for your patience :)

**Comment by baregl** [comment]
I've removed some extra padding, since the "Show PSP games" item was already cut off when the search is active.

**Comment by baregl** [comment]
Please pull my latest commit in my repo (or do it yourself), I screwed up the link formatting in item 8

**Comment by blastrock** [comment]
Done

**Pull request closed without merging**
