### PR TITLE
[LiveArea] slightly updated LiveArea app design

### PR DESCRIPTION
**Pull request by JesterIOS**
**[29.07.18/PS]** p.r. based on #147 

Hello, again.
A few days ago I decided to update the LiveArea app style.

What's new:

- Updated **Icon0**
- Updated **StartUp**
- Changed **template.xml**

So... how it looks on the **PSVITA/PSTV**:

42860597-8bd46c4c-8a81-11e8-8a6b-1d193556a5ba

### CODE REVIEW

**Comment by nkrapivin** [comment]
Looks good!
VitaShell style? ;)

**Comment by JesterIOS** [comment]
@nkrapivin, yeah. "VitaShell" LiveArea design is a good example of how should looks VITA/TV homebrews.

**Comment by blastrock** [comment]
Oh I didn't see you already patched it, thanks!

**Comment by blastrock** [comment]
Merged as c490c1b

**Pull request closed without merging**
